export const fakeJobs = [
   {
    id: "1",
    title: "Frontend Developer",
    company: "TechCorp",
    location: "New York, NY",
    type: "Full-Time",
    category: "Engineering",
    description: "Join our team to build amazing UI with React.",
    requirements: "3+ years of experience with React.js",
    benefits: "Health insurance, Remote friendly",
  },
  {
    id: "1",
    title: "Frontend Developer",
    company: "TechCorp",
    location: "New York, NY",
    type: "Full-Time",
    category: "Engineering",
    description: "Join our team to build amazing UI with React.",
    requirements: "3+ years of experience with React.js",
    benefits: "Health insurance, Remote friendly",
  },
  {
    id: "2",
    title: "Product Designer",
    company: "DesignHub",
    location: "Remote",
    type: "Part-Time",
    category: "Design",
    description: "We’re looking for a UX/UI designer.",
    requirements: "Strong portfolio and Figma skills",
    benefits: "Flexible hours, Remote work",
  },

  // New jobs below
  {
    id: "3",
    title: "Backend Engineer",
    company: "DataMasters",
    location: "San Francisco, CA",
    type: "Full-Time",
    category: "Engineering",
    description: "Develop and maintain scalable backend services.",
    requirements: "5+ years with Node.js or Python",
    benefits: "401(k), Stock options, Gym membership",
  },
  {
    id: "4",
    title: "Marketing Specialist",
    company: "BrandWave",
    location: "Austin, TX",
    type: "Full-Time",
    category: "Marketing",
    description: "Plan and execute marketing campaigns.",
    requirements: "Experience with digital marketing and SEO",
    benefits: "Health insurance, Remote options",
  },
  {
    id: "5",
    title: "Data Analyst",
    company: "InsightAnalytics",
    location: "Chicago, IL",
    type: "Contract",
    category: "Data Science",
    description: "Analyze data trends and create reports.",
    requirements: "Proficient with SQL and Excel",
    benefits: "Flexible schedule, Remote work",
  },
  {
    id: "6",
    title: "Mobile App Developer",
    company: "AppPros",
    location: "Remote",
    type: "Full-Time",
    category: "Engineering",
    description: "Build mobile apps for iOS and Android platforms.",
    requirements: "Experience with React Native or Flutter",
    benefits: "Remote friendly, Health benefits",
  },
  {
    id: "7",
    title: "Content Writer",
    company: "WriteRight",
    location: "Boston, MA",
    type: "Part-Time",
    category: "Content",
    description: "Create engaging blog posts and articles.",
    requirements: "Excellent writing and editing skills",
    benefits: "Flexible hours, Work from home",
  },
  {
    id: "8",
    title: "HR Manager",
    company: "PeopleFirst",
    location: "Seattle, WA",
    type: "Full-Time",
    category: "Human Resources",
    description: "Lead recruiting and employee relations.",
    requirements: "5+ years HR experience",
    benefits: "Health and dental, Paid time off",
  },
  {
    id: "9",
    title: "Sales Executive",
    company: "SalesPro",
    location: "Denver, CO",
    type: "Full-Time",
    category: "Sales",
    description: "Drive revenue growth through client acquisition.",
    requirements: "Strong communication and negotiation skills",
    benefits: "Commission, Health insurance",
  },
  {
    id: "10",
    title: "DevOps Engineer",
    company: "CloudNet",
    location: "New York, NY",
    type: "Full-Time",
    category: "Engineering",
    description: "Maintain CI/CD pipelines and cloud infrastructure.",
    requirements: "Experience with AWS and Docker",
    benefits: "Stock options, Flexible hours",
  },
  {
    id: "11",
    title: "Customer Support Specialist",
    company: "HelpDesk Inc.",
    location: "Remote",
    type: "Full-Time",
    category: "Support",
    description: "Assist customers with product issues via email and phone.",
    requirements: "Customer service experience preferred",
    benefits: "Remote work, Paid training",
  },
  {
    id: "12",
    title: "Graphic Designer",
    company: "Creativa",
    location: "Los Angeles, CA",
    type: "Contract",
    category: "Design",
    description: "Design marketing materials and branding assets.",
    requirements: "Proficient with Adobe Creative Suite",
    benefits: "Flexible schedule",
  },
];
